---
kind: pipeline
type: docker
name: default

steps:
# note zest does everything, including tagging!
- name: version-tag-changelog
  image: python:3-bookworm
  commands:
  #- git config --global user.email "zest.releaser@example.com"
  #- git config --global user.name "Zest Releaser"
  #- git remote set-url origin ${DRONE_GIT_SSH_URL}
  #- git config --global push.autoSetupRemote true
  - pip --no-cache-dir install zest.releaser
  # TODO: consider towncrier for changelog updates
  #- pip install --no-cache-dir zestreleaser.towncrier
  - fullrelease --no-input
  #- git push origin --tags
  when:
    branch:
    - master

- name: git-push
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: github_ssh_key
    #remote_name: origin
    #branch: "${DRONE_BRANCH}"
    #remote: ssh://git@github.com/laur89/deluge-autoremoveplus.git
    remote: "${DRONE_GIT_SSH_URL}"
    force: false
    followtags: true
  when:
    branch:
    - master

- name: build
  image: python:3-alpine
  commands:
  - pip install --no-cache-dir setuptools
  - python setup.py bdist_egg
  when:
    event: tag

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - dist/*
    title: "${DRONE_TAG}"
    #note: CHANGELOG.md
    checksum:
       - sha256
  when:
    event: tag

trigger:
  ref:
  - refs/heads/master
  #- refs/heads/develop
  - refs/heads/feature/*
  - refs/tags/*
